name: Keep Alive

on:
  schedule:
    - cron: '0 12 1,15 * *'  # runs on the 1st and 15th of every month at noon UTC

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Gigalixir
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: |
          git remote add gigalixir https://git.gigalixir.com/metrics.git/
          git -c http.extraHeader="Authorization: Basic $(echo -n '${{ secrets.GIGALIXIR_EMAIL }}:${{ secrets.GIGALIXIR_API_KEY }}' | base64 -w 0)" push gigalixir main